### ISSUE TITLE
Incompatibility with gantry

### ISSUE THREAD

**Issue by elecoest** [phproberto/joomla-twig#51]
with this simple code :

JLoader::import('twig.library');
echo Twig::render('@component/com_allevents/events/agenda.twig');

I obtain : 

Warning: count(): Parameter must be an array or an object that implements Countable in /home/alleve87/public_html/plugins/system/gantry/gantry.php on line 406

Error: Argument 1 passed to Gantry\Component\Twig\TwigNodeTry::__construct() must be an instance of Twig_NodeInterface, instance of Twig_Node given, called in /home/alleve87/public_html/libraries/gantry5/classes/Gantry/Component/Twig/TokenParserTry.php on line 49: Argument 1 passed to Gantry\Component\Twig\TwigNodeTry::__construct() must be an instance of Twig_NodeInterface, instance of Twig_Node given, called in /home/alleve87/public_html/libraries/gantry5/classes/Gantry/Component/Twig/TokenParserTry.php on line 49

Of course I use a Gantry template :)

Do you have any idea ?

**Comment by phproberto** [comment]
Hi @elecoest ,

I think the main issue is that your gantry template is using Twig v1 and this library uses Twig v2. This is exactly why I created this package. To allow extensions like grantry, etc. to ship their specific logic without having to worry about Twig version. But this needs time and willing to use standard packages.

I don't use Gantry but I have a `guess` fix for you if you want to `hack` gantry. **I don't really recommend it** but it will help you to also report the issue to them.

In the line 49 of the file:
`/home/alleve87/public_html/libraries/gantry5/classes/Gantry/Component/Twig/TokenParserTry.php`

You have a `__construct()` method with the first parameter type casted to `\Twig_NodeInterface`. You can replace that with: `\Twig_Node` and it should work.

I'm not going to create a `joomla-twig` version compatible with the old Twig v1 because it's a new library and the idea is that developers adopt it in their future releases. It makes no sense to ask them to rewrite their packages to use an obsolete Twig version. The best moment for them to start using ´joomla-twig` is when updating their extensions to use Twig v2.

**Comment by phproberto** [comment]
I'm closing this. Please feel free to reopen it if you think my information was wrong.

Thanks for using this joomla-twig :heart:
